version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    networks:
      - web
    command: ["sh", "./start.sh"]
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    depends_on:
      - postgres_db

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:3000"
    networks:
      - web
    volumes:
    - ./frontend/:/app
    depends_on:
      - backend

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/ar/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - web

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - web
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
